### ISSUE TITLE
Add more exercises to Day 1.

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#158]
I think we need to add at least 1 hard exercise to Types and List.

Some things we could consider adding:

- Tuples (Intro)
- Creating your own case class (Types)

**Comment by ssanj** [comment]
I think Tuples would be good as they are used in the `foldLeft` exercises later on. Maybe we could update the Wallet exercise such that the students create the data type.

**Comment by ssanj** [comment]
It would also be good to have an example of pattern matching a nested case class to really show how useful it can be.

**Comment by ssanj** [comment]
See #168
