### ISSUE TITLE
Calculating `min` is weird.

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#196]
In reality I would use `NonEmptyList.from(list)` and then `reduce` on the NEL.

But here people have to fold on the `tail` and it feels so odd.

Maybe we can rewrite this into an exercise where we concatenate a bunch of strings together?

Or to reverse a list?

**Comment by wjlow** [comment]
Hey @lukestephenson did you find this a little awkward too?

**Comment by lukestephenson-zendesk** [comment]
Agree that `NonEmptyList` would be a better approach, but not sure we want to introduce that.  I think people are learning from the exercise as it is.
