### ISSUE TITLE
Deprioritise zip exercises.

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#206]
I think zipping isn't very important in this course. If we de-prioritise it (put it in the bonus section), we can bump `getNames`, `getAdults` and `reverseList`, which are exercises to rewrite imperative code in a functional way. I ran this recently and found that it was valuable.

Or we could introduce `collect` here to prepare students for `Exception` and `Either` exercises.

**Comment by wjlow** [comment]
@lukestephenson what do you think?

**Comment by lukestephenson** [comment]
Introducing `collect` requires introducing partial functions.  Given option exercises already introduces the "for" comprehension, I think it would be better to delay introducing "collect" to limit the concepts introduced too early.

I agree zipping isn't hugely important, but I didn't find it to be a problem.  The hints basically said what to do, so it didn't block anyone.  And the use of tuples reenforced earlier learning from lesson 1 which I liked.
