### ISSUE TITLE
Add exercise to rewrite some domain models that use inheritance to an ADT.

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#210]
This is a proposal to add an additional section to `TypesExercises`. 

Here's an example that enforces that every constructor of `User` requires an `id` and `lastSeen` using a more traditional OO approach, where parameters are _inherited_ from the base class.

Remember **we want to enforce that every `User` has an `id` and `lastSeen`**

```
sealed trait User {
  val id: String
  val lastSeen: LocalDate
}

case class LoggedInUser(id: String, lastSeen: LocalDate, email: Email) extends User

case class AnonymousUser(id: String, lastSeen: LocalDate) extends User
```

The alternative is to favour composition:

```
sealed trait UserType
case class LoggedInUser(email: Email) extends UserType
case object AnonymousUser extends UserType

case class User(userType: UserType, id: String, lastSeen: LocalDate)
```

This alternative also enforces that every `User` must have an `id` and `lastSeen`.

Thoughts?

**Comment by sanjivsahayamrea** [comment]
Yep, love it. I think we need to have a convincing argument as to why this is better than inheritance.

- There is a SOC between a User data and the type of a User
- It's also easier to add more common parameters directly into `User` without modifying multiple classes. (In the old way if you added a new field to `User`, you would also have to update `LoggedInUser` and `AnonymousUser` which means everywhere they are used in Prod and Test code.

**Comment by lukestephenson-zendesk** [comment]
Agree with @sanjivsahayamrea .

**Comment by wjlow** [comment]
I'm reluctant to add material without removing any existing ones, however.

Would we be okay removing the `zip` exercises in List?

Or perhaps move them down the Bonus line?

**Comment by sanjivsahayamrea** [comment]
I think it's nice to have the `zip` example because it's unusual and you will eventually need to use it in real work. Making it bonus content is fine by me. :)

**Comment by wjlow** [comment]
Ive decided that we won't add this due to time constraints
