### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#233]

**Comment by george-wilson-rea** [comment]
Perhaps you should move to Github Actions instead.

**Comment by ssanj** [comment]
Perhaps
![](https://media.giphy.com/media/7qqR23PvcgLaU/giphy.gif)

PR: https://github.com/wjlow/intro-to-scala/pull/240

**Comment by ssahayam-zd** [comment]
I think we can close this.
