### ISSUE TITLE
TyperExercises.showTrafficLightStr extension

### ISSUE THREAD

**Issue by ssanj** [wjlow/intro-to-scala#36]
To support the extension of TyperExercises.showTrafficLightStr:

> We have a new traffic light called Flashing, with a frequency, e.g. "flashing 20", "flashing 100"
>
> Extend `showTrafficLightStr` that you have just implemented above to support this new functionality.

should we mention:

> Hint: String.split and pattern match on Array

or were you thinking of introducing regexs here?

```
"""flashing\s\(d+)""".r
```

**Comment by wjlow** [comment]
Hmm I was thinking of splitting and pattern matching.

My regex-fu is non-existent.

What do you think?

**Comment by sanjivsahayamrea** [comment]
I'll create the regex and update the comments.

**Comment by ssanj** [comment]
added regex to #44
