### ISSUE TITLE
When do we introduce `case` in `map`/`filter` etc?

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#55]
First exercise that uses it is `showEveryNthPerson`

**Comment by felipeeflores** [comment]
I think ListExercises are a good spot for introducing it. It is a bit early, but ExceptionExercises would be even uglier to implement without it.  Probably a brief explanation on `showEveryNthPerson` is ok, but then explain in more depth as it gets used in more complex scenarios.

**Comment by ashokkumar** [comment]
I too felt that, but we are introducing the ```case match``` on person in TypeExecises, so I think it's fair enough to assume people are used to it.

May be we can add a hint and make it more explicit.

**Comment by wjlow** [comment]
I've added more hints:

https://github.com/wjlow/intro-to-scala/pull/86
