### ISSUE TITLE
Add presenters names against schedule

### ISSUE THREAD

**Issue by ssanj** [wjlow/intro-to-scala#67]
It would be useful to have the presenters names against their scheduled items.

<img src="https://media1.giphy.com/media/l4FGq09sQSls3Aufm/giphy.gif?cid=e1bb72ff5ae9daeb56464a397716480d" width="100%" />

**Comment by wjlow** [comment]
I don't want to put the presenter names here since it's a public GitHub repo and the presenters might change the next time we run it. Can we just keep it pinned on the Slack channel?

**Comment by wjlow** [comment]
Done with initials
