### ISSUE TITLE
Flashing with Frequency in TypeExercises

### ISSUE THREAD

**Issue by sanjivsahayamrea** [wjlow/intro-to-scala#72]
Adding a Flashing with a *frequency* to [TypeExercises](https://github.com/wjlow/intro-to-scala/blob/master/src/main/scala/fundamentals/level02/TypesExercises.scala) makes this a little too complex as:

- We need to explain Regex matching or
- Explain splitting and matching on Array.

If we get rid of the *frequency* this exercise will be much easier and we can easily demonstrate the compile-checked exhaustiveness.

```
  /**
    * We have a new traffic light called Flashing, with a frequency, e.g. "flashing 20", "flashing 100"
    *
    * Extend `showTrafficLightStr` that you have just implemented above to support this new functionality.
    *
    * Use a test driven approach to implement this new functionality.
    *
    * scala> showTrafficLightStr("flashing 20")
    * = "The traffic light is flashing with a frequency of 20"
    *
    * scala> showTrafficLightStr("flashing 100")
    * = "The traffic light is flashing with a frequency of 100"
    *
    * Hint: Use flashing regex and pattern matching or 
    * use `.split(" ")` and pattern-match on `Array("flashing", frequency)`
    **/

  val flashing = """^flashing\s(\d+)$""".r
```

**Comment by wjlow** [comment]
I agree.

How do we show exhaustiveness check?

Perhaps the presenter could just add a new kind of light `Blue` and show that the compiler gives a warning.

And then move on?

**Comment by sanjivsahayamrea** [comment]
We add `Flashing` but it doesn't take in a `frequency`. It's just like every other case object. That way we can avoid matching on Regexes and on `Array`s.

**Comment by wjlow** [comment]
Good idea
