### ISSUE TITLE
Remove validPerson from ExceptionExercises

### ISSUE THREAD

**Issue by sanjivsahayamrea** [wjlow/intro-to-scala#73]
Should we remove validPerson from [ExceptionExercises](https://github.com/wjlow/intro-to-scala/blob/master/src/main/scala/fundamentals/level03/ExceptionExercises.scala)?

```
 def createValidPeople: List[Person] = ???
```

and just use:

```
def createValidPeople2: List[Person] = ???
```

We are trying to demonstrate that you have to use hacks when you use Exceptions as values.

**Comment by wjlow** [comment]
Yup.

Since `createValidPeople` is unused. Just skip straight to `createValidPeople2` and show them how hard it is.

**Comment by ssanj** [comment]
removed in #82
