### ISSUE TITLE
Remove mkTrafficLightOrNull exercises from NullExercises

### ISSUE THREAD

**Issue by sanjivsahayamrea** [wjlow/intro-to-scala#74]
Remove mkTrafficLightOrNull exercises from [NullExercises](https://github.com/wjlow/intro-to-scala/blob/master/src/main/scala/fundamentals/level03/NullExercises.scala):

```
def mkTrafficLightOrNull(str: String): TrafficLight = ???
def mkTrafficLightOrNullThenShow(str: String): String = ???
```

as these are covered by the Person exercises:

```
def mkPersonOrNull(name: String, age: Int): Person = ???
def mkPersonOrNullThenChangeName(oldName: String, age: Int, newName: String): Person = ???
```

**Comment by sanjivsahayamrea** [comment]
If it's easy and quick => keep repetition in.

**Comment by wjlow** [comment]
Let’s keep this in.
