### ISSUE TITLE
Remove `curriedAdd`

### ISSUE THREAD

**Issue by wjlow** [wjlow/intro-to-scala#78]
`curriedAdd` in [IntroExercises](https://github.com/wjlow/intro-to-scala/blob/master/src/main/scala/fundamentals/level01/IntroExercises.scala) may not be very useful because we don't use currying later on.

Feels like a distraction.

**Comment by felipeeflores** [comment]
I agree unless we intend to use it later on. The concept is not valuable at this point. Feels like an item that doesn't take you anywhere.
